module.exports = [
  {
    id: 1,
    subject: "Maths",
    price: 85,
    location: "Manchester",
    spaces: 6,
    icon: "calculator",
  },
  {
    id: 2,
    subject: "English",
    price: 80,
    location: "Oxford",
    spaces: 7,
    icon: "calculator",
  },
  {
    id: 3,
    subject: "Music",
    price: 95,
    location: "London",
    spaces: 10,
    icon: "book",
  },
  {
    id: 4,
    subject: "English",
    price: 75,
    location: "Bristol",
    spaces: 5,
    icon: "book",
  },
  {
    id: 5,
    subject: "Maths",
    price: 70,
    location: "Bristol",
    spaces: 7,
    icon: "music",
  },
  {
    id: 6,
    subject: "Maths",
    price: 100,
    location: "London",
    spaces: 5,
    icon: "calculator",
  },
  {
    id: 7,
    subject: "Maths",
    price: 90,
    location: "Oxford",
    spaces: 8,
    icon: "calculator",
  },
  {
    id: 8,
    subject: "English",
    price: 100,
    location: "London",
    spaces: 6,
    icon: "book",
  },
  {
    id: 9,
    subject: "English",
    price: 80,
    location: "York",
    spaces: 9,
    icon: "book",
  },
  {
    id: 10,
    subject: "Music",
    price: 60,
    location: "Bristol",
    spaces: 7,
    icon: "music",
  },
];
